// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.josephabel.native_dialog_plus

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object FlutterBindingsPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** The presentation style of the dialog. */
enum class DialogStyle(val raw: Int) {
  /** Bottom action sheet (CupertinoActionSheet equivalent). */
  ACTION_SHEET(0),
  /** Modal alert dialog (CupertinoAlertDialog equivalent). */
  ALERT(1);

  companion object {
    fun ofRaw(raw: Int): DialogStyle? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The visual style of an individual action button. */
enum class ActionStyle(val raw: Int) {
  /** Standard button. */
  DEFAULT_STYLE(0),
  /** Cancel button. */
  CANCEL(1),
  /** Destructive / delete button. */
  DESTRUCTIVE(2);

  companion object {
    fun ofRaw(raw: Int): ActionStyle? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A single button in the dialog.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DialogAction (
  val text: String,
  val style: ActionStyle,
  val enabled: Boolean,
  /**
   * ARGB color for the button text (Flutter's Color.toARGB32()).
   * Null means the platform default is used.
   */
  val color: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DialogAction {
      val text = pigeonVar_list[0] as String
      val style = pigeonVar_list[1] as ActionStyle
      val enabled = pigeonVar_list[2] as Boolean
      val color = pigeonVar_list[3] as Long?
      return DialogAction(text, style, enabled, color)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      style,
      enabled,
      color,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DialogAction) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterBindingsPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Arguments for showing a native dialog.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ShowDialogArgs (
  val title: String? = null,
  val message: String? = null,
  val cancellable: Boolean,
  val style: DialogStyle,
  val actions: List<DialogAction>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ShowDialogArgs {
      val title = pigeonVar_list[0] as String?
      val message = pigeonVar_list[1] as String?
      val cancellable = pigeonVar_list[2] as Boolean
      val style = pigeonVar_list[3] as DialogStyle
      val actions = pigeonVar_list[4] as List<DialogAction>
      return ShowDialogArgs(title, message, cancellable, style, actions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      message,
      cancellable,
      style,
      actions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ShowDialogArgs) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterBindingsPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class FlutterBindingsPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DialogStyle.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ActionStyle.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DialogAction.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ShowDialogArgs.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DialogStyle -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ActionStyle -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is DialogAction -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ShowDialogArgs -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Flutter → Native API.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NativeDialogHostApi {
  /**
   * Shows the dialog and returns the index of the tapped action,
   * or null if the dialog was dismissed without a selection.
   */
  fun showDialog(args: ShowDialogArgs, callback: (Result<Long?>) -> Unit)

  companion object {
    /** The codec used by NativeDialogHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterBindingsPigeonCodec()
    }
    /** Sets up an instance of `NativeDialogHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeDialogHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_dialog_plus.NativeDialogHostApi.showDialog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val argsArg = args[0] as ShowDialogArgs
            api.showDialog(argsArg) { result: Result<Long?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FlutterBindingsPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FlutterBindingsPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
