// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsFlutterBindings(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsFlutterBindings(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsFlutterBindings(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashFlutterBindings(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashFlutterBindings(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashFlutterBindings(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// The presentation style of the dialog.
enum DialogStyle: Int {
  /// Bottom action sheet (CupertinoActionSheet equivalent).
  case actionSheet = 0
  /// Modal alert dialog (CupertinoAlertDialog equivalent).
  case alert = 1
}

/// The visual style of an individual action button.
enum ActionStyle: Int {
  /// Standard button.
  case defaultStyle = 0
  /// Cancel button.
  case cancel = 1
  /// Destructive / delete button.
  case destructive = 2
}

/// A single button in the dialog.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DialogAction: Hashable {
  var text: String
  var style: ActionStyle
  var enabled: Bool
  /// ARGB color for the button text (Flutter's Color.toARGB32()).
  /// Null means the platform default is used.
  var color: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DialogAction? {
    let text = pigeonVar_list[0] as! String
    let style = pigeonVar_list[1] as! ActionStyle
    let enabled = pigeonVar_list[2] as! Bool
    let color: Int64? = nilOrValue(pigeonVar_list[3])

    return DialogAction(
      text: text,
      style: style,
      enabled: enabled,
      color: color
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      style,
      enabled,
      color,
    ]
  }
  static func == (lhs: DialogAction, rhs: DialogAction) -> Bool {
    return deepEqualsFlutterBindings(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFlutterBindings(value: toList(), hasher: &hasher)
  }
}

/// Arguments for showing a native dialog.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ShowDialogArgs: Hashable {
  var title: String? = nil
  var message: String? = nil
  var cancellable: Bool
  var style: DialogStyle
  var actions: [DialogAction]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ShowDialogArgs? {
    let title: String? = nilOrValue(pigeonVar_list[0])
    let message: String? = nilOrValue(pigeonVar_list[1])
    let cancellable = pigeonVar_list[2] as! Bool
    let style = pigeonVar_list[3] as! DialogStyle
    let actions = pigeonVar_list[4] as! [DialogAction]

    return ShowDialogArgs(
      title: title,
      message: message,
      cancellable: cancellable,
      style: style,
      actions: actions
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      message,
      cancellable,
      style,
      actions,
    ]
  }
  static func == (lhs: ShowDialogArgs, rhs: ShowDialogArgs) -> Bool {
    return deepEqualsFlutterBindings(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFlutterBindings(value: toList(), hasher: &hasher)
  }
}

private class FlutterBindingsPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DialogStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ActionStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return DialogAction.fromList(self.readValue() as! [Any?])
    case 132:
      return ShowDialogArgs.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FlutterBindingsPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DialogStyle {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ActionStyle {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? DialogAction {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? ShowDialogArgs {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FlutterBindingsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterBindingsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterBindingsPigeonCodecWriter(data: data)
  }
}

class FlutterBindingsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FlutterBindingsPigeonCodec(readerWriter: FlutterBindingsPigeonCodecReaderWriter())
}


/// Flutter → Native API.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeDialogHostApi {
  /// Shows the dialog and returns the index of the tapped action,
  /// or null if the dialog was dismissed without a selection.
  func showDialog(args: ShowDialogArgs, completion: @escaping (Result<Int64?, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeDialogHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FlutterBindingsPigeonCodec.shared }
  /// Sets up an instance of `NativeDialogHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeDialogHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Shows the dialog and returns the index of the tapped action,
    /// or null if the dialog was dismissed without a selection.
    let showDialogChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_dialog_plus.NativeDialogHostApi.showDialog\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showDialogChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let argsArg = args[0] as! ShowDialogArgs
        api.showDialog(args: argsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      showDialogChannel.setMessageHandler(nil)
    }
  }
}
