// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// The presentation style of the dialog.
enum DialogStyle {
  /// Bottom action sheet (CupertinoActionSheet equivalent).
  actionSheet,
  /// Modal alert dialog (CupertinoAlertDialog equivalent).
  alert,
}

/// The visual style of an individual action button.
enum ActionStyle {
  /// Standard button.
  defaultStyle,
  /// Cancel button.
  cancel,
  /// Destructive / delete button.
  destructive,
}

/// A single button in the dialog.
class DialogAction {
  DialogAction({
    required this.text,
    required this.style,
    required this.enabled,
    this.color,
  });

  String text;

  ActionStyle style;

  bool enabled;

  /// ARGB color for the button text (Flutter's Color.toARGB32()).
  /// Null means the platform default is used.
  int? color;

  List<Object?> _toList() {
    return <Object?>[
      text,
      style,
      enabled,
      color,
    ];
  }

  Object encode() {
    return _toList();  }

  static DialogAction decode(Object result) {
    result as List<Object?>;
    return DialogAction(
      text: result[0]! as String,
      style: result[1]! as ActionStyle,
      enabled: result[2]! as bool,
      color: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DialogAction || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Arguments for showing a native dialog.
class ShowDialogArgs {
  ShowDialogArgs({
    this.title,
    this.message,
    required this.cancellable,
    required this.style,
    required this.actions,
  });

  String? title;

  String? message;

  bool cancellable;

  DialogStyle style;

  List<DialogAction> actions;

  List<Object?> _toList() {
    return <Object?>[
      title,
      message,
      cancellable,
      style,
      actions,
    ];
  }

  Object encode() {
    return _toList();  }

  static ShowDialogArgs decode(Object result) {
    result as List<Object?>;
    return ShowDialogArgs(
      title: result[0] as String?,
      message: result[1] as String?,
      cancellable: result[2]! as bool,
      style: result[3]! as DialogStyle,
      actions: (result[4] as List<Object?>?)!.cast<DialogAction>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ShowDialogArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is DialogStyle) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ActionStyle) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is DialogAction) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is ShowDialogArgs) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DialogStyle.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ActionStyle.values[value];
      case 131: 
        return DialogAction.decode(readValue(buffer)!);
      case 132: 
        return ShowDialogArgs.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Flutter → Native API.
class NativeDialogHostApi {
  /// Constructor for [NativeDialogHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeDialogHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Shows the dialog and returns the index of the tapped action,
  /// or null if the dialog was dismissed without a selection.
  Future<int?> showDialog(ShowDialogArgs args) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.native_dialog_plus.NativeDialogHostApi.showDialog$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[args]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as int?);
    }
  }
}
